### ISSUE TITLE
数据库的一个问题

### ISSUE THREAD

**Issue by QponahuijiuY** [YUbuntu0109/SSM-SMS#12]
不好意思，又打扰一下。
看来那个地址必须是网上的地址，本地的地址不行，我昨天试了我本地的一张图片，登陆之后直接报报异常，现在我又把数据库的图片地址改成了的网图地址，现在能登陆上去了，

谢谢大佬分享。~~~~~

**Comment by GoogTech** [comment]
*我真的不明白你想表达什么 ! 请使用配套的数据库 : https://github.com/YUbuntu0109/SSM-SMS/tree/master/database%20file*
