### ISSUE TITLE
can be deployed by embed tomcat？

### ISSUE THREAD

**Issue by snowden-fu** [YUbuntu0109/SSM-SMS#4]
i have searched plugin about embed tomcat, but i am not sure whether runnable or not.
https://mvnrepository.com/artifact/org.apache.tomcat.maven

**Comment by snowden-fu** [comment]
https://stackoverflow.com/questions/26883836/tomcat-8-maven-plugin-for-java-8

**Comment by GoogTech** [comment]
🍻 Personal needs ~
