### ISSUE TITLE
jsp page invalid in index.jsp

### ISSUE THREAD

**Issue by snowden-fu** [YUbuntu0109/SSM-SMS#5]
https://github.com/YUbuntu0109/SSM-SMS/blob/ce9a28398798ddbb34b09c1b1a3258c0801e5fde/sms/src/main/webapp/index.jsp#L9

**Comment by snowden-fu** [comment]
it is my mistake

**Comment by GoogTech** [comment]
:heart: `index.jsp` is an important file to enter the controller !

**Comment by snowden-fu** [comment]
you are right, just i didn't see the path in the controller.
