### ISSUE TITLE
修改密码

### ISSUE THREAD

**Issue by loggest** [YUbuntu0109/SSM-SMS#8]

**Comment by YUbuntu0109** [comment]
🥂  Please try to click the buttom of modifying password · · ·

> 
> 
> 打开这个窗口没有弹出对话框
> ![changePassword](https://user-images.githubusercontent.com/42573412/61113712-67492100-a4c1-11e9-84a5-1559836d9022.PNG)

🥂  Please try to click the buttom of modifying password · · ·

**Comment by GoogTech** [comment]
> 
> 
> 打开这个窗口没有弹出对话框
> ![changePassword](https://user-images.githubusercontent.com/42573412/61113712-67492100-a4c1-11e9-84a5-1559836d9022.PNG)

🥂  Please try to click the buttom of modifying password · · ·
